theme: jekyll-theme-slate
name: m1ghtfr3e
---

![](https://github.com/m1ghtfr3e/COVID-19-Analyzation/blob/img/conf-dead.jpg)
![](https://github.com/m1ghtfr3e/COVID-19-Analyzation/blob/img/conf-rec-CN.jpeg)


